function [magn,t] = importfile2(filename, startRow, endRow)
% UTILIZZATO PER IMPORTARE FILE DEL SECONDO DATASET



%IMPORTFILE1 Import numeric data from a text file as a matrix.
%   HIP = IMPORTFILE1(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   HIP = IMPORTFILE1(FILENAME, STARTROW, ENDROW) Reads data from rows
%   STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   Hip = importfile1('Hip.txt', 6, 29360);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2014/12/11 23:41:27

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 6;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
Data = [dataArray{1:end-1}];
magn = sqrt(Data(:,2).^2 + Data(:,3).^2 + Data(:,4).^2);
t = Data(:,1);